feat: support loading types from ethPM Manifest
vyperlang/vyper pull request #2628
Opened 2022-02-04 01:03 UTC by fubuloubu

### What I did
Allow loading ABI types from ethPM manifest files

### How I did it
Hacking

### How to verify it
The whole imports system needs a lot of work

### Description for the changelog
Load interfaces from an ethPM Manifest file

### Cute Animal Picture

![Put a link to a cute animal picture inside the parenthesis-->]()

2022-02-07 20:26 UTC, charles-cooper requested changes

2022-02-07 20:26 UTC, charles-cooper commented on vyper/cli/vyper_compile.py
> +                    if "contractTypes" in contents:
add a comment explaining this is handling ethPM v3 files

2022-02-07 20:27 UTC, charles-cooper commented
also maybe add a test

2022-02-07 20:27 UTC, fubuloubu commented on vyper/cli/vyper_compile.py
> +                    if "contractTypes" in contents:
```suggestion
                    # EthPM Manifest (EIP-2678)
                    if "contractTypes" in contents:
```

2022-02-07 20:27 UTC, fubuloubu commented on vyper/cli/vyper_compile.py
> +                    elif "abi" in contents or isinstance(contents, list):
```suggestion
                    # ABI JSON file (either `{"abi": List[ABI]}` or `List[ABI]`)
                    elif "abi" in contents or isinstance(contents, list):
```

2022-02-07 20:27 UTC, fubuloubu commented on vyper/cli/utils.py
> +        # Handle ethPM Manifests
```suggestion
        # Handle ethPM Manifests (`from path.to.Manifest import InterfaceName`)
```

2022-02-08 01:32 UTC, fubuloubu commented
Tested locally by using Brownie (which uses JSON mode to compile) and downloaded copy of OpenZeppelin/openzeppelin-contracts converted to ethPM manifest format (using Ape)

2022-02-08 01:39 UTC, fubuloubu commented
Like to note this code is really hacky and should be refactored so it finds the different types of interfaces faster:
```py
from location import Bar  # can either be `location/Bar.{vy|json}` or `location.json:Bar`
```

2022-02-11 22:25 UTC, charles-cooper approved these changes

2022-02-11 22:26 UTC, merged