feat: ecrecover copy solidity interface
vyperlang/vyper pull request #3084
Opened 2022-09-06 07:16 UTC by pandadefi

### What I did

Since vyper has uint8 now, ecrecover v should be using uint8.

### How I did it

### How to verify it

### Commit message

Commit message for the final, squashed PR. (Optional, but reviewers will appreciate it! Please see [our commit message style guide](../../blob/master/docs/style-guide.rst#best-practices-1) for what we would ideally like to see in a commit message.)

### Description for the changelog

### Cute Animal Picture

![Put a link to a cute animal picture inside the parenthesis-->]()

2022-09-06 13:42 UTC, fubuloubu approved these changes
This tracks how we do it in `ape` (which I've always had to convert over) and how Solidity also handles it with it's `ecrecover`, so I support this update

Probably needs to go and update any `ecrecover` tests, and also this is a *breaking* change that probably needs to wait for `v0.4.0` to merge (what do you think @big-tech-sux?)

2022-09-06 16:39 UTC, charles-cooper commented
well, v0.4.0 is the next release so we can probably start merging in breaking changes.

in any case(!) i think this change is small enough that we don't need to wait for v0.4.0 and we could merge it as part of the 0.3.x series.

2022-09-06 21:10 UTC, fubuloubu commented
> well, v0.4.0 is the next release so we can probably start merging in breaking changes.
> 
> in any case(!) i think this change is small enough that we don't need to wait for v0.4.0 and we could merge it as part of the 0.3.x series.

I disagree, this will definitely require at least a twitter shout out (above and beyond the release notes) telling people about this change so they can make updates to their code accordingly.

2022-09-08 15:57 UTC, charles-cooper approved these changes
This seems fine. The only thing I am hesitant about is that conversions to uint8 (which this change will encourage the user to do) introduce extra opcodes to ensure the value is in bounds for uint8. This probably should not stop us from making the interface cleaner, but it's something to keep in mind.

2022-09-08 16:17 UTC, charles-cooper requested changes
sorry based on offline conversation with @fubuloubu -- @pandadefi since point of this PR is just to make it syntactically simpler to call ecrecover with an existing uint8 (without having to `convert()`) but the ecrecover precompile just expects 32 bytes, it would introduce inefficiency for use cases where the user has a `uint256` (since those are always checked to be in range for v anyways).

to address this, i think we should make ecrecover accept both kinds of input. in other words, `v` can be in `(uint8, uint256)` and r and s in `(bytes32, uint256)`. this maintains backwards compatibility while supporting the intent of this PR. the only downside is that it makes the API more confusing, but there is no EVM-level reason to pick one of these types over another.

2022-09-14 12:32 UTC, fubuloubu approved these changes

2022-09-15 16:40 UTC, charles-cooper commented on README.md
> +```bas
```suggestion
```bash
```

2022-09-21 01:06 UTC, charles-cooper approved these changes

2022-09-21 01:09 UTC, merged

2022-09-21 01:09 UTC, charles-cooper commented
@pandadefi thanks for your contribution!