refactor(docker): reduce img size
vyperlang/vyper pull request #3120
Opened 2022-10-11 08:43 UTC by sambacha

ignore explicit

### What I did

### How I did it

### How to verify it

### Commit message

Commit message for the final, squashed PR. (Optional, but reviewers will appreciate it! Please see [our commit message style guide](../../blob/master/docs/style-guide.rst#best-practices-1) for what we would ideally like to see in a commit message.)

2022-10-11 18:00 UTC, fubuloubu approved these changes
Seems okay, need some QA to show that the images are equivalent and nothing got ignored that shouldn't be

2022-10-14 13:09 UTC, fubuloubu commented
> this is a dup of #3111

I'll say the same thing I said there, hopefully @sambacha confirms or makes an update: I see a few vyper-related files that I would expect to be in the build for it to function properly. That's why it needs some QA to see if it still functions correctly with the slimmed down fileset

2022-11-23 17:19 UTC, charles-cooper requested changes
blocking this because it doesn't include data that is needed for producing `vyper --version` output

2023-04-07 02:47 UTC, charles-cooper commented on .dockerignore
> +vyper/vyper_git_commithash.txt
```suggestion
```

2023-04-09 22:46 UTC, sambacha commented
Let me update this later today for ya

2025-06-17 13:49 UTC, charles-cooper approved these changes
i think this is fine. we can include it in the next release

2026-08-12 18:23 UTC, closed without merging