support '_' separator in dec/oct/float numbers
vyperlang/vyper pull request #3665
Opened 2023-11-08 15:49 UTC by z80dev

Allows 100_000 in place of 100000

### What I did

modified grammar defining decimal, octal, and float numbers to match what vyper actually accepts and compiles

### How I did it

### How to verify it

### Commit message

Commit message for the final, squashed PR. (Optional, but reviewers will appreciate it! Please see [our commit message style guide](../../master/docs/style-guide.rst#best-practices-1) for what we would ideally like to see in a commit message.)

### Description for the changelog

### Cute Animal Picture

![Put a link to a cute animal picture inside the parenthesis-->](https://i.insider.com/60d0aae33093db0019702380?width=700)

2023-11-20 15:48 UTC, charles-cooper approved these changes

2023-11-20 15:50 UTC, charles-cooper requested changes
looks like the new grammar breaks some tests

2025-06-25 20:55 UTC, charles-cooper approved these changes

2025-06-26 07:53 UTC, cyberthirst commented
Please add tests for all supported types. Also add tests for edgecases like _0, 10__0, 10_,  0xaa__aa etc

2026-02-13 08:41 UTC, Sporarum reviewed
Very nice, a couple comments but nothing major

Don't forget to add tests for the uppercase variants as well

2026-02-13 08:41 UTC, Sporarum commented on vyper/ast/parse.py
Nitpick: I would put ignoring underscores here

2026-02-13 08:41 UTC, Sporarum commented on vyper/ast/grammar.lark
> +BIN_NUMBER.2 : /0b_?[0-1](_?[0-1])*/i
Isn't this equivalent ?
```suggestion
HEX_NUMBER.2: /0x(_?[\da-f])+/i
OCT_NUMBER.2: /0o(_?[0-7])+/
BIN_NUMBER.2 : /0b(_?[0-1])+/i
```

Furthermore, we should also accept uppercase:
```suggestion
HEX_NUMBER.2: /0[xX](_?[\da-f])+/i
OCT_NUMBER.2: /0[oO](_?[0-7])+/
BIN_NUMBER.2 : /0[bB](_?[0-1])+/i
```

See https://peps.python.org/pep-0515/#literal-grammar

2026-02-13 08:41 UTC, Sporarum commented on vyper/ast/grammar.lark
> +FLOAT_NUMBER.2: /((\d+(_\d+)*\.(\d+(_\d+)*)?|\.\d+(_\d+)*)(e[-+]?\d+)?|\d+(_\d+)*(e[-+]?\d+))/i
This is getting too complicated to parse, consider breaking it using smaller parsers
The split as in https://peps.python.org/pep-0515/#literal-grammar seems acceptable (see "for floating point ...")

2026-02-13 08:42 UTC, Sporarum commented
Oh and the title of the commit/PR should be more explicit about this only affecting the lark grammar, since we usually use the python parser

2026-02-13 12:25 UTC, cyberthirst commented on vyper/ast/parse.py
agreed, i think it's better to treat all values consistently and have them share the property of having the underscores replaced

2026-02-13 14:06 UTC, merged