chore: improve diagnostics for invalid for loop annotation
vyperlang/vyper pull request #3721
Opened 2024-01-08 06:00 UTC by tserg

### What I did

Improve diagnostics for invalid loop variable annotation and add tests for #3596.

Compiling this contract throws an error that does not make sense
```
@external
def foo():
    for i: uint9 in [1, 2, 3]:
        pass
```
```
vyper.exceptions.UnknownType: No builtin or user-defined type named '@exte'. 
  contract "tmp/old_for.vy:1", function "foo", line 1:0 
  ---> 1 @external
  -------^
       2 def foo():
```

This PR changes the error message to:
```
vyper.exceptions.UnknownType: No builtin or user-defined type named 'uint9'. Did you mean 'uint96', or maybe 'uint8'?
  contract "tmp/old_for.vy:3", function "foo", line 3:4 
       2 def foo():
  ---> 3     for i: uint9 in [1, 2, 3]:
  -----------^
       4         pass
```

### How I did it

Propagate the annotation source code and `For` node locations to the annotation and all its child nodes

### How to verify it

See tests.

### Commit message

```
chore: improve diagnostics for invalid for loop annotation
```

### Description for the changelog

Improve diagnostics for invalid for loop annotation

### Cute Animal Picture

![Put a link to a cute animal picture inside the parenthesis-->](https://www.reddit.com/media?url=https%3A%2F%2Fi.redd.it%2Fpz7qltuhh9g71.jpg)

2024-01-08 16:06 UTC, charles-cooper commented on vyper/ast/parse.py
> +            python_ast.copy_location(n, node)
i think `python_ast.increment_lineno` might be better here

2024-01-08 16:09 UTC, charles-cooper requested changes
nice new tests.

i think the annotation is a bit tricky to get right, since you're copying the location of the parent `for` node into the for target. here's a (contrived) example of where that doesn't work so well:
```vyper
@external
def foo():
    for i: \
        \
        \
        \
        uint9 in [1, 2, 3]:
        pass
```
with the current implementation that results in an error message something like
```vyper
vyper.exceptions.UnknownType: No builtin or user-defined type named 'uint9'. Did you mean 'uint96', or maybe 'uint8'?
  contract "repros/3721.vy:3", function "foo", line 3:4 
       2 def foo():
  ---> 3     for i: \
  -----------^
       4         \
```
i think what we really want to do is go into the tokens generated by ASTTokens (https://asttokens.readthedocs.io/en/latest/api-index.html#asttokens.ASTTokens.tokens) and modify all of them to have the correct start/end offsets.

2024-01-11 02:30 UTC, tserg commented on vyper/ast/parse.py
> +                    endpos=n.first_token.startpos + og_target.first_token.startpos,
```suggestion
                    endpos=n.first_token.endpos + og_target.first_token.startpos,
```
Should this be `endpos`?

2024-01-11 02:41 UTC, tserg commented on vyper/ast/parse.py
> +                    endpos=n.first_token.startpos + og_target.first_token.startpos,
False alarm.

2024-01-11 22:42 UTC, charles-cooper commented
i have a solution for https://github.com/vyperlang/vyper/pull/3721#pullrequestreview-1809505443. i'll submit it in a follow up PR.

2024-01-11 22:42 UTC, charles-cooper approved these changes

2024-01-11 22:42 UTC, merged