feat[venom]: add codesize optimization pass
vyperlang/vyper pull request #4333
Opened 2024-10-27 14:37 UTC by charles-cooper

### What I did
basic codesize optimization which strengthens large literals to evm computations which are shorter

### How I did it

### How to verify it

### Commit message

Commit message for the final, squashed PR. (Optional, but reviewers will appreciate it! Please see [our commit message style guide](../../master/docs/style-guide.rst#best-practices-1) for what we would ideally like to see in a commit message.)

### Description for the changelog

### Cute Animal Picture

![Put a link to a cute animal picture inside the parenthesis-->]()

2024-10-29 08:19 UTC, harkal commented on vyper/venom/passes/literals_codesize.py
> +            i += 1
```suggestion
        for inst in bb.instructions:
```

2024-10-29 08:21 UTC, harkal commented on vyper/venom/passes/literals_codesize.py
> +            if val == (2**256 - 1):
Make use of constants that we have for numbers like these

2024-10-29 08:27 UTC, harkal commented on vyper/venom/passes/literals_codesize.py
> +            if (ix := binz.find("0")) > 8:  # `not` is 1 byte
Maybe, extract 8 and 24 to constants like `BITS_FOR_SHL` and `BITS_FOR_NOT`?

2024-10-29 08:30 UTC, harkal commented on vyper/venom/passes/literals_codesize.py
> +                inst.operands = [IRLiteral(val >> ix), IRLiteral(ix)]
```suggestion

                # sanity check
                assert (val >> ix) << ix == val, val
                assert (val >> ix) & 1 == 1

                inst.opcode = "shl"
                inst.operands = [IRLiteral(val >> ix), IRLiteral(ix)]
```

2024-10-29 08:33 UTC, harkal commented on vyper/venom/passes/literals_codesize.py
> +    def _process_bb(self, bb):
For readability, it might be a good thing to add comments to "separate" the three rules the processing applies, or make them separate methods?

2024-10-29 08:34 UTC, harkal requested changes
I have made some comments in the code above. Additionally, we could add some tests for the optimization cases.

2024-11-20 14:26 UTC, charles-cooper commented
@cyberthirst could you take a look at the tests and see if you want to add any cases?

2024-12-20 16:57 UTC, HodanPlodky approved these changes

2024-12-20 17:27 UTC, harkal approved these changes

2024-12-20 17:33 UTC, merged